/**
 * Phase 1 + Phase 2: Sample Templates
 * Built-in design samples to get started quickly
 */

const SAMPLES = [
  {
    id: 'options_menu',
    name: 'オプションメニュー',
    description: 'ActionBarにオプションメニューを持つシンプルな画面',
    icon: '☰',
    components: [
      {
        id: 'menu_title_1',
        type: 'TextView',
        props: {
          id: 'tvTitle',
          text: 'オプションメニューのサンプル',
          textSize: '18sp',
          textColor: '#212121',
          fontStyle: 'bold',
          gravity: 'center',
          width: 'match_parent',
          height: 'wrap_content',
          padding: '16dp',
          margin: '0dp',
        },
      },
      {
        id: 'menu_desc_1',
        type: 'TextView',
        props: {
          id: 'tvDesc',
          text: '右上の ⋮ アイコンをタップするとメニューが表示されます。',
          textSize: '14sp',
          textColor: '#757575',
          gravity: 'center',
          width: 'match_parent',
          height: 'wrap_content',
          padding: '8dp',
          margin: '8dp',
        },
      },
      {
        id: 'menu_comp_1',
        type: 'Menu',
        props: {
          id: 'optionsMenu',
          title: 'Options',
          items: '設定\nヘルプ\nこのアプリについて',
        },
      },
    ],
  },
  {
    id: 'list_view',
    name: 'リストビュー',
    description: 'RecyclerViewを使ったリスト表示サンプル',
    icon: '📋',
    components: [
      {
        id: 'list_header_1',
        type: 'TextView',
        props: {
          id: 'tvListHeader',
          text: 'アイテムリスト',
          textSize: '20sp',
          textColor: '#212121',
          fontStyle: 'bold',
          width: 'match_parent',
          height: 'wrap_content',
          padding: '16dp',
          margin: '0dp',
          gravity: 'start',
        },
      },
      {
        id: 'list_comp_1',
        type: 'RecyclerView',
        props: {
          id: 'recyclerView',
          width: 'match_parent',
          height: 'match_parent',
          layoutManager: 'LinearLayoutManager',
          orientation: 'vertical',
          hasFixedSize: true,
          itemDecoration: 'DividerItemDecoration',
          padding: '0dp',
          margin: '0dp',
        },
      },
      {
        id: 'list_fab_1',
        type: 'FloatingActionButton',
        props: {
          id: 'fabAdd',
          src: '@drawable/ic_add',
          contentDescription: '追加',
          backgroundTint: '#6200EE',
          layout_gravity: 'bottom|end',
          margin: '16dp',
        },
      },
    ],
  },
  {
    id: 'list_select',
    name: 'リスト選択',
    description: 'スピナーとラジオボタンで選択するサンプル',
    icon: '🔽',
    components: [
      {
        id: 'sel_title_1',
        type: 'TextView',
        props: {
          id: 'tvSelectTitle',
          text: '選択してください',
          textSize: '18sp',
          textColor: '#212121',
          fontStyle: 'bold',
          width: 'match_parent',
          height: 'wrap_content',
          padding: '16dp',
          margin: '0dp',
          gravity: 'start',
        },
      },
      {
        id: 'sel_spinner_1',
        type: 'Spinner',
        props: {
          id: 'categorySpinner',
          width: 'match_parent',
          height: 'wrap_content',
          entries: '選択肢1\n選択肢2\n選択肢3\n選択肢4',
          padding: '4dp',
          margin: '8dp',
          prompt: 'カテゴリを選択',
        },
      },
      {
        id: 'sel_radio_1',
        type: 'RadioButton',
        props: {
          id: 'radioOption1',
          text: 'オプション A',
          checked: true,
          textSize: '16sp',
          padding: '4dp',
          margin: '8dp',
        },
      },
      {
        id: 'sel_radio_2',
        type: 'RadioButton',
        props: {
          id: 'radioOption2',
          text: 'オプション B',
          checked: false,
          textSize: '16sp',
          padding: '4dp',
          margin: '4dp',
        },
      },
      {
        id: 'sel_radio_3',
        type: 'RadioButton',
        props: {
          id: 'radioOption3',
          text: 'オプション C',
          checked: false,
          textSize: '16sp',
          padding: '4dp',
          margin: '4dp',
        },
      },
      {
        id: 'sel_btn_1',
        type: 'MaterialButton',
        props: {
          id: 'confirmButton',
          text: '確認',
          width: 'match_parent',
          height: 'wrap_content',
          backgroundTint: '#6200EE',
          textColor: '#FFFFFF',
          padding: '8dp',
          margin: '16dp',
        },
      },
    ],
  },
  {
    id: 'login_form',
    name: 'ログインフォーム',
    description: 'MaterialデザインのログインUI',
    icon: '🔐',
    components: [
      {
        id: 'login_logo_1',
        type: 'ImageView',
        props: {
          id: 'ivLogo',
          width: '100dp',
          height: '100dp',
          src: '@drawable/ic_launcher',
          contentDescription: 'アプリロゴ',
          scaleType: 'fitCenter',
          padding: '0dp',
          margin: '32dp',
        },
      },
      {
        id: 'login_title_1',
        type: 'TextView',
        props: {
          id: 'tvLoginTitle',
          text: 'ようこそ',
          textSize: '26sp',
          textColor: '#212121',
          fontStyle: 'bold',
          gravity: 'center',
          width: 'match_parent',
          height: 'wrap_content',
          margin: '8dp',
        },
      },
      {
        id: 'login_email_1',
        type: 'EditText',
        props: {
          id: 'etEmail',
          hint: 'メールアドレス',
          inputType: 'textEmailAddress',
          width: 'match_parent',
          padding: '8dp',
          margin: '8dp',
          imeOptions: 'actionNext',
        },
      },
      {
        id: 'login_pass_1',
        type: 'EditText',
        props: {
          id: 'etPassword',
          hint: 'パスワード',
          inputType: 'textPassword',
          width: 'match_parent',
          padding: '8dp',
          margin: '8dp',
          imeOptions: 'actionDone',
        },
      },
      {
        id: 'login_btn_1',
        type: 'MaterialButton',
        props: {
          id: 'btnLogin',
          text: 'ログイン',
          width: 'match_parent',
          backgroundTint: '#6200EE',
          textColor: '#FFFFFF',
          cornerRadius: '8dp',
          padding: '8dp',
          margin: '16dp',
          textAllCaps: false,
        },
      },
      {
        id: 'login_register_1',
        type: 'MaterialButton',
        props: {
          id: 'btnRegister',
          text: 'アカウントを作成',
          width: 'match_parent',
          style: 'outlined',
          backgroundTint: 'transparent',
          textColor: '#6200EE',
          strokeColor: '#6200EE',
          strokeWidth: '1dp',
          padding: '8dp',
          margin: '4dp',
          textAllCaps: false,
        },
      },
    ],
  },
  {
    id: 'settings',
    name: '設定画面',
    description: 'スイッチとスライダーを使った設定画面',
    icon: '⚙️',
    components: [
      {
        id: 'settings_title_1',
        type: 'TextView',
        props: {
          id: 'tvSettingsTitle',
          text: 'アプリ設定',
          textSize: '22sp',
          textColor: '#212121',
          fontStyle: 'bold',
          width: 'match_parent',
          padding: '16dp',
          margin: '0dp',
        },
      },
      {
        id: 'settings_notify_1',
        type: 'Switch',
        props: {
          id: 'switchNotifications',
          text: 'プッシュ通知',
          checked: true,
          textSize: '16sp',
          padding: '4dp',
          margin: '8dp',
        },
      },
      {
        id: 'settings_dark_1',
        type: 'Switch',
        props: {
          id: 'switchDarkMode',
          text: 'ダークモード',
          checked: false,
          textSize: '16sp',
          padding: '4dp',
          margin: '8dp',
        },
      },
      {
        id: 'settings_analytics_1',
        type: 'CheckBox',
        props: {
          id: 'checkAnalytics',
          text: '使用状況データの共有を許可',
          checked: true,
          textSize: '14sp',
          padding: '4dp',
          margin: '8dp',
        },
      },
      {
        id: 'settings_font_label_1',
        type: 'TextView',
        props: {
          id: 'tvFontSizeLabel',
          text: 'フォントサイズ',
          textSize: '16sp',
          textColor: '#424242',
          padding: '4dp',
          margin: '8dp',
        },
      },
      {
        id: 'settings_slider_1',
        type: 'Slider',
        props: {
          id: 'sliderFontSize',
          value: 16,
          valueFrom: 10,
          valueTo: 30,
          stepSize: 1,
          thumbColor: '#6200EE',
          trackColor: '#6200EE',
          width: 'match_parent',
          margin: '8dp',
        },
      },
    ],
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = SAMPLES;
}
